name: virtual_env_fraud
dependencies:
  - pip
  - python=3.12
  - pip:
      - numpy==2.1.2
      - pandas==2.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - six==1.16.0
      - tzdata==2024.2
      - selenium
      - plotly
      - matplotlib
      - streamlit
      - altair
      - webdriver-manager
      - networkx
      - transformers
      - wikipedia
      - redis
      - openai
      - PyPDF2
      - pdfminer.six
      - llmsherpa
      - pytesseract
      - pdf2image
      - fitz
      - PyMuPDF
      - pdfplumber
      - adjustText